### ISSUE TITLE
How to properly parse trajectories / missing files?

### ISSUE THREAD

**Issue by sachit-menon** [Berkeley-NLP/Agent-Eval-Refine#1]
Hi, thanks for this amazing work! I really appreciate that you've released things so comprehensively, including the emulator code and everything in one nice repo. 

I was trying to parse some of the trajectories, specifically from `webarena-reflexion-oracle-eval`, and I think I might be missing something. I wanted to see what the model sees for the trajectories leading to the outcome; I see "image_paths" as a key to the jsons in the `records` folder, but many of them refer to images that are not present in the `images` folder. 

For example, `"outputs/mar22-all-gpt4-baseline-temp0-noUAhint-r1/images/0_0_0.png` in the `0_0.json` example -- the only folder included with the zip is r3, and the `images` folder for that has no `0_0_0.png`. 

Am I misunderstanding how to parse this? Are some files missing? I also noticed the `renders` folder -- what would be the easiest way to visualize the trajectories like I'm hoping to? Thanks!

**Comment by Jiayi-Pan** [comment]
Hi, thank you for the kind words:)
I am pretty occupied right now and will try to get back to you by next Monday.

**Comment by sachit-menon** [comment]
Thanks!
________________________________

**Comment by 594zyc** [comment]
Hi @sachit-menon 

Thanks for your interest in your work! It seems that some of the images are not correctly copied from baseline runs to the experiment runs. We will fix it soon. 

To visualize the trajectories, you can preview the HTML files under `renders`. The images are encoded as base64 strings there thus should not have the above problem.

**Comment by 594zyc** [comment]
Fixed

**Comment by sachit-menon** [comment]
Hi @594zyc , thanks for the pointer to the renders; they've been very interesting to parse. One thing I'm missing -- do the renders show what the actual feedback from the evaluator was? (And beyond that, what the captions were for the caption-based ones?)

Also, do you happen to have the renders for the AgentTrajectories / CogAgent experiments, or is there a script that makes it easy to create them?

**Comment by 594zyc** [comment]
Hi @sachit-menon , the renders only show the agent trajectories. The evaluator's feedbacks are recorded in the markdown files under `eval`. With the latest trajectories you should also be able to see the images embedded in the md files.

**Comment by Jiayi-Pan** [comment]
Hi sachit, renders is in fact a built-in feature of webarena, and isn't available for other environments. 
However, it should still be easy to inspect these trajectories with our annotation app
```
python -m agent_eval.eval.annotate_app --dataset <path-to-dataset> --log_name <log-name>
```

**Comment by sachit-menon** [comment]
Thanks both of you!
