### ISSUE TITLE
Evaluating the WebArena Agent

### ISSUE THREAD

**Issue by abwilf** [Berkeley-NLP/Agent-Eval-Refine#3]
Hi there,

I've been trying to run the eval scripts for web, but seems like only GPT-4v is supported? It seems like the evaluator version that's needed is "final-v3", but the function "final_eval_v3" isn't implemented in Evaluator.py.

Please let me know how I can access this! I'd like to evaluate with open source models.

Best,
Alex

**Comment by Jiayi-Pan** [comment]
Hi @abwilf thanks for you interests in the project:)
I accidentally deleted that function when preparing the code release, it is fixed in the latest commit now!

**Comment by Jiayi-Pan** [comment]
closing the issue now, let me know if you have any other questions!

**Comment by abwilf** [comment]
Thank you!
