### ISSUE TITLE
Question about WebArena baseline implementations in paper

### ISSUE THREAD

**Issue by tongyx361** [Berkeley-NLP/Agent-Eval-Refine#4]
> This agent achieves an end-to-end task success rate of 14.4% using the oracle evaluator.

> Figure 3 shows "Baseline success rate w/o Reflexion" is 15.6% and Oracle Evaluator always helps,

Are these two results in conflict?

**Comment by Jiayi-Pan** [comment]
Thanks for the catch. 14.4% is from WebArena's official paper. However, our reproduction yields 15.6%, which is "Baseline success rate w/o Reflexion".
We will add a foodnote in the next iteration of the paper to make it clear

**Comment by tongyx361** [comment]
Thanks for your reply. But I don't understand what does "using the oracle evaluator" mean for the result "from WebArena's official paper"?

**Comment by Jiayi-Pan** [comment]
14.4% is WebArena officially released result without reflexion, 15.6% is our reproduction with 0 round of reflexion (essentially no reflexion).
We then equipped this agent with different evaluators and see how external feedbacks improves the agent. And oracle evaluator is used as the strict upper bound.

**Comment by tongyx361** [comment]
So "This agent achieves an end-to-end task success rate of 14.4% using the oracle evaluator" is not precise? Actually the WebArena official result uses no evaluator?

**Comment by Jiayi-Pan** [comment]
Aha, sorry for the confusion. You are definitely correct and it's my bad. 
What we intended to mean here is the 14.4% success rate is evaluated using the oracle evaluator. We will fix the wording in the next iteration of paper.

**Comment by tongyx361** [comment]
I see. Thanks for your patience!
