### ISSUE TITLE
Annotation results from autonomous evaluator for WebArena trajectories.

### ISSUE THREAD

**Issue by dayvidwang** [Berkeley-NLP/Agent-Eval-Refine#6]
Hello, thank you for your work! It is very interesting and I wanted to do some further inspection of how Autonomous Evaluation performs on WebArena trajectories. In particular, I'd like to see how each of the evaluator models (GPT-4V, captioner + GPT-4, and Captioner + Mixtral) does on specific tasks from WebArena. Do you have the data for the evaluator results for each task in WebArena anywhere? I was not able to find it.

For example, ideally I would be able to have a dictionary of each task ID and the predicted success/failure from each evaluator. Something like this:

```
{
  "123": {
    "gpt-4-captioner": True,
    "gpt-4v": True,
    "mixtral-captioner": False
  }
}
```

**Comment by Jiayi-Pan** [comment]
Thank you for your interest in our work. Unfortunately, I regret that I didn’t save the fine-grained logs. 
However, the results should be fully reproducible by running the evaluation scripts available in the repository after downloading the trajectories from [here](https://huggingface.co/datasets/Agent-Eval-Refine/Agent-Trajectories).
